name: "Compile Mermaid"

on:
  push:
    paths:
      - "_README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -e '.*\.md$' | xargs)"
      - name: markdown files changed
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: compile mermaid
        uses: neenjaw/compile-mermaid-markdown-action@0.3.1
        with:
          files: ${{ steps.getfile.outputs.files }}
          output: ".resources"
        env:
          HIDE_CODEBLOCKS: 1
          ABSOLUTE_IMAGE_LINKS: 1
          OUTPUT_FILE_TYPE: "svg"